stages:
  - test
  - build
  - deploy_dev

django tests:
  stage: test
  image: python:3-alpine
  script:
    - pip install -r requirements.txt
    - python manage.py migrate blog
    - python manage.py test
  tags:
    - docker


docker build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t registry.gitlab.com/msdos760/docker-cicd-django .
    - docker push registry.gitlab.com/msdos760/docker-cicd-django
  tags:
    - docker
