stages:
  - test
  - build
  - deploy_dev

before_script:
  - |
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      tag="latest"
      echo " Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
    else
      tag="$CI_COMMIT_REF_SLUG"
      echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
    fi

django tests:
  stage: test
  image: python:3-alpine
  script:
    - pip install -r requirements.txt
    - mkdir db
    - python manage.py migrate
    - python manage.py test
  tags:
    - dev
docker build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

  tags:
    - dev